version: '3'
services:     
  app:
    image: myapp
    build: ./app
    ports:
      - '3000:3000'
    volumes: 
      - ./app:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: database
    build: ./db
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_DATABASE: 'comm'
      MYSQL_PASSWORD: '19031973Mother'
      MYSQL_ROOT_PASSWORD: '19031973Mother'
      MYSQL_ALLOW_EMPTY_PASSWORD: '19031973Mother'
      MYSQL_RANDOM_ROOT_PASSWORD: '19031973Mother'
    restart: always
    ports: 
      - '3307:3307'

volumes:
    db-config:
    db-data: